class Request(var method: String = "",
              var protocol: String = "",
              var protocolVersion: String = "",
              var url: String = "",
              var host: String = "",
              var headers: MutableMap<String, String> = mutableMapOf(),
              var cookie: String = "",
              var contentType: Content = Content.NONE,
              var body: String = "",
              var params: MutableMap<String, String> = mutableMapOf(),
              var args: MutableMap<String, String> = mutableMapOf(),
)